# KIS OpenAPI Configuration
kis:
  mode: "virtual"
  virtual:
    hts_id: "@2877359"
    app_key: "PSRln4nKF3ovkPvV417D8aBPidh2yurHmL6C"
    app_secret: "0M7h1bPRjPP2X1F0V0Yv1nopqvAo/kwmKlvOPKWIBuQmYvlqYBFhdylZ7Ew/RVHIIDln08Ac9AD1AMoVjLheABLj28RknNN6n7pgewiZEouiPE/EWV/hLNQ6dpr+uWtLCmKBDufwSnyKoqzgltYqqYIw4t1+AYn93huvykHMX8f35GXldxg="
    account: "997867"
  real:
    hts_id: "@2877359"
    app_key: "PSJhDVK33YAo1fzKgJXgW3OXoDNZU3PkWIgH"
    app_secret: "+2YUrAJiQtGpg3FBn2+x/pY3sNSZrmziM6f4+HBQzSva8WaYCCba/XzUL7rCB/TbkpyC6efB50RdBA7sfhPK9MxN692k1cpah6+6IEcE/2Z53jxd7chdrMDQzNdeO2fn03Nt4BjhdVQh7ehY4DWNoi7HZQSghjkfbW52MkHUxcbVhBc/OGA="
    account: "44080555-01"

# 자동매매 안전장치
safety:
  max_order_pct: 15
  max_daily_orders: 10
  daily_loss_limit_pct: -3
  require_confirmation: true
